"""
PDF Forensics Analyser
Detects structural and metadata anomalies in PDF documents.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import fitz  # PyMuPDF


KNOWN_PAYROLL_PRODUCERS = [
    "myob", "xero", "keypay", "employment hero", "sage", "meridian",
    "preceda", "chris21", "aurion", "micropay", "elmo", "astute",
    "microsoft word", "microsoft excel",  # some SMEs generate from Office
    "libreoffice", "openoffice",
]

SUSPICIOUS_PRODUCERS = [
    "canva", "adobe photoshop", "adobe illustrator", "gimp",
    "inkscape", "paint", "snagit",
]


@dataclass
class Flag:
    category: str
    code: str
    title: str
    description: str
    severity: str  # low | medium | high | critical
    weight: int    # 1-10
    evidence: dict[str, Any] = field(default_factory=dict)
    document_id: str | None = None


def analyse(file_path: str, doc_type: str = "payslip", document_id: str | None = None) -> list[Flag]:
    """Run all PDF forensic checks on a file. Returns list of Flags."""
    flags: list[Flag] = []
    path = Path(file_path)

    if not path.exists():
        return [Flag(
            category="pdf_forensics", code="FILE_NOT_FOUND",
            title="Document file not found",
            description=f"The uploaded file could not be located at {file_path}.",
            severity="critical", weight=10, document_id=document_id,
        )]

    try:
        doc = fitz.open(file_path)
    except Exception as exc:
        return [Flag(
            category="pdf_forensics", code="PDF_PARSE_ERROR",
            title="PDF could not be parsed",
            description=f"The file could not be opened as a valid PDF: {exc}",
            severity="critical", weight=10, document_id=document_id,
        )]

    meta = doc.metadata or {}

    # --- Metadata checks ---
    flags += _check_producer(meta, doc_type, document_id)
    flags += _check_timestamps(meta, document_id)
    flags += _check_fonts(doc, document_id)
    flags += _check_images(doc, document_id)
    flags += _check_javascript(doc, document_id)

    doc.close()
    return flags


def _check_producer(meta: dict, doc_type: str, doc_id: str | None) -> list[Flag]:
    flags = []
    producer = (meta.get("producer") or "").lower().strip()
    creator = (meta.get("creator") or "").lower().strip()
    combined = producer + " " + creator

    is_known_payroll = any(k in combined for k in KNOWN_PAYROLL_PRODUCERS)
    is_suspicious = any(s in combined for s in SUSPICIOUS_PRODUCERS)

    if is_suspicious:
        flags.append(Flag(
            category="pdf_forensics",
            code="SUSPICIOUS_PDF_CREATOR",
            title=f"Document created with design/image editing software",
            description=(
                f"The PDF was created with '{meta.get('creator') or meta.get('producer')}'. "
                f"Legitimate {doc_type}s are generated by payroll platforms (Xero, MYOB, KeyPay, etc.), "
                f"not graphic design tools. This is a strong indicator of document fabrication."
            ),
            severity="critical",
            weight=9,
            evidence={"producer": meta.get("producer"), "creator": meta.get("creator")},
            document_id=doc_id,
        ))
    elif not is_known_payroll and doc_type in ("payslip", "bank_statement"):
        blank = not producer.strip() and not creator.strip()
        flags.append(Flag(
            category="pdf_forensics",
            code="UNKNOWN_PDF_PRODUCER",
            title="PDF producer is unknown or blank",
            description=(
                f"The PDF producer field is '{meta.get('producer') or 'blank'}' and creator is "
                f"'{meta.get('creator') or 'blank'}'. Legitimate payslips from payroll software "
                f"always identify their generating application."
            ),
            severity="high" if blank else "medium",
            weight=6 if blank else 4,
            evidence={"producer": meta.get("producer"), "creator": meta.get("creator")},
            document_id=doc_id,
        ))

    return flags


def _parse_pdf_date(date_str: str | None) -> datetime | None:
    if not date_str:
        return None
    # PDF date format: D:YYYYMMDDHHmmSSOHH'mm'
    m = re.match(r"D:(\d{4})(\d{2})(\d{2})(\d{2})?(\d{2})?(\d{2})?", date_str or "")
    if not m:
        return None
    try:
        year, month, day = int(m.group(1)), int(m.group(2)), int(m.group(3))
        hour = int(m.group(4) or 0)
        minute = int(m.group(5) or 0)
        second = int(m.group(6) or 0)
        return datetime(year, month, day, hour, minute, second, tzinfo=timezone.utc)
    except ValueError:
        return None


def _check_timestamps(meta: dict, doc_id: str | None) -> list[Flag]:
    flags = []
    now = datetime.now(tz=timezone.utc)
    creation = _parse_pdf_date(meta.get("creationDate"))
    modification = _parse_pdf_date(meta.get("modDate"))

    if creation and creation > now:
        flags.append(Flag(
            category="pdf_forensics", code="FUTURE_CREATION_DATE",
            title="Document creation date is in the future",
            description=f"The PDF metadata shows a creation date of {creation.date()}, which is in the future. This is impossible for a genuine document.",
            severity="critical", weight=10,
            evidence={"creation_date": str(creation)},
            document_id=doc_id,
        ))

    if creation and modification:
        delta_hours = (modification - creation).total_seconds() / 3600
        if delta_hours > 1:
            flags.append(Flag(
                category="pdf_forensics", code="DOCUMENT_MODIFIED_AFTER_CREATION",
                title="Document was modified after initial creation",
                description=(
                    f"The PDF was created on {creation.date()} but last modified on {modification.date()} "
                    f"({delta_hours:.0f} hours later). Genuine payslips are generated once and not edited."
                ),
                severity="high",
                weight=7,
                evidence={"creation_date": str(creation), "modification_date": str(modification), "delta_hours": round(delta_hours, 1)},
                document_id=doc_id,
            ))

    return flags


def _check_fonts(doc: fitz.Document, doc_id: str | None) -> list[Flag]:
    flags = []
    all_fonts: set[str] = set()

    for page in doc:
        try:
            blocks = page.get_text("dict").get("blocks", [])
            for block in blocks:
                for line in block.get("lines", []):
                    for span in line.get("spans", []):
                        font_name = span.get("font", "").split("+")[-1]  # strip subset prefix
                        if font_name:
                            all_fonts.add(font_name)
        except Exception:
            continue

    if len(all_fonts) > 4:
        flags.append(Flag(
            category="pdf_forensics", code="EXCESSIVE_FONT_VARIETY",
            title=f"Unusual number of fonts detected ({len(all_fonts)})",
            description=(
                f"The document uses {len(all_fonts)} different font families. "
                f"Machine-generated payslips from payroll software typically use 1-2 fonts. "
                f"Excessive font variety indicates manual text insertion or AI editing."
            ),
            severity="medium",
            weight=5,
            evidence={"font_count": len(all_fonts), "fonts": sorted(all_fonts)[:20]},
            document_id=doc_id,
        ))

    return flags


def _check_images(doc: fitz.Document, doc_id: str | None) -> list[Flag]:
    flags = []
    for page_num, page in enumerate(doc):
        try:
            images = page.get_images(full=True)
            text = page.get_text("text").strip()
            if images and len(text) < 50:
                flags.append(Flag(
                    category="pdf_forensics", code="TEXT_IN_IMAGE_ONLY",
                    title="Page content is embedded in an image, not as text",
                    description=(
                        f"Page {page_num + 1} contains {len(images)} image(s) with minimal extractable text. "
                        f"This pattern is consistent with a scanned document that has been digitally altered — "
                        f"a common technique to hide manipulation."
                    ),
                    severity="medium",
                    weight=5,
                    evidence={"page": page_num + 1, "image_count": len(images), "text_length": len(text)},
                    document_id=doc_id,
                ))
        except Exception:
            continue

    return flags


def _check_javascript(doc: fitz.Document, doc_id: str | None) -> list[Flag]:
    """JavaScript in a payslip/bank statement PDF is extremely suspicious."""
    flags = []
    try:
        js = doc.get_javascript()
        if js:
            flags.append(Flag(
                category="pdf_forensics", code="JAVASCRIPT_IN_PDF",
                title="PDF contains embedded JavaScript",
                description="JavaScript was found embedded in this document. Financial documents have no legitimate reason to contain JavaScript and this may indicate a malicious or fabricated file.",
                severity="critical", weight=10,
                evidence={"javascript_length": len(js)},
                document_id=doc_id,
            ))
    except Exception:
        pass
    return flags
